version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./www:/www
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./www:/www
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - code-network
    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=password
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports:
            - "8082:80"
        environment:
            - PMA_USER=root
            - PMA_PASSWORD=password
            - PHP_UPLOAD_MAX_FILESIZE=100MB

networks:
    code-network:
        driver: bridge
